networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
# custom_networks_here

services:
# DEFAULT CONTAINER
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  vscode:
    image: lscr.io/linuxserver/code-server
    container_name: vscode
    restart: unless-stopped
    ports:
      - 2222:8443
    environment:
      - PUID=0
      - GUID=0
      - TZ=Europe/Berlin
      # - PASSWORD=password_placeholder
    volumes:
      - ./volumes/vscode/config:/config
      - ./:/ei23-docker